import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    languagesSidebar: [{type: 'autogenerated', dirName: 'languages'}],
    toolsSidebar: [{type: 'autogenerated', dirName: 'tools'}],
    conventionsSidebar: [{type: 'autogenerated', dirName: 'conventions'}],
    conceptsSidebar: [{type: 'autogenerated', dirName: 'concepts'}]
};

export default sidebars;
